server:
  name: "sync_chain"
  address:     ":8000"
  workId: 1
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  msgSize: 1000000

jaegerUrl: "127.0.0.1:6831"

logger:
  level : "all"
  stdout: true 
  rotateExpire: "1d"
  path: "./"
  logger1:
    level : "all"
    stdout: true 
    rotateExpire: "1d"
    path: "./"

database:
  sync_chain:
  - link: "pgsql:postgres:123456@tcp(123.60.148.168:10100)/sync_chain"
  riskcontrol:
  - link: "mysql:ssh:123456@tcp(127.0.0.1:3305)/riskcontrol"

cache:
  sessionDuration: 2000

nrpc:
  natsUrl: "127.0.0.1:4222"

chainini: "./chain.ini"

# redis 
redis:
  default:
    address: 127.0.0.1:10060
    db:      1
  cache:
    address:     127.0.0.1:10060
    db:          2

