// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"syncChain/internal/dao/internal"
)

// internalChainDataDao is internal type for wrapping internal DAO implements.
type internalChainDataDao = *internal.ChainDataDao

// chainDataDao is the data access object for table chain_data.
// You can define custom methods on it to extend its functionality as you wish.
type chainDataDao struct {
	internalChainDataDao
}

var (
	// ChainData is globally public accessible object for table chain_data operations.
	ChainData = chainDataDao{
		internal.NewChainDataDao(),
	}
)

// Fill with you ideas below.
